eureka:
  client:
    registryFetchIntervalSeconds: 5
    healthcheck:  
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
server: 
  port: 8081
spring:
  application:  
    name: serverclient